### ISSUE TITLE
Anyone know how to get Hulu Favorites/Subscriptions?

### ISSUE THREAD

**Issue by samgreco** [CodePenguin/PlayPass#5]
Tried this and a couple of variation, but no luck.

		<pass enabled="1" description="Hulu Subscriptions">
			<scan name="Hulu">
				<scan name="Your Subscriptions">
					<scan name="*">
						<queue name="*" />
					</scan>
				</scan>
			</scan>
		</pass>

I get this output:

Processing pass "Hulu Favorites Subscriptions"...
Matching "Hulu"...
  Matching "Your Subscriptions"...
    Matching "*"...
      Matching "*"...
      Matching "*"...
      Matching "*"...
      Matching "*"...
      Matching "*"...
      Matching "*"...
        No matches "*".
      Matching "*"...
        No matches "*".
      Matching "*"...
        No matches "*".
      Matching "*"...
        No matches "*".
Finished processing pass "Hulu Favorites Subscriptions"...

**Comment by CodePenguin** [comment]
When things are working the way you think they should, verbose mode is the best way to see what is going on.  It will give you much more details about what is being matched.
`PlayPass.exe -verbose`

In the case of the Hulu Subscriptions, you need one more level of scanning.  I'd recommend using "Full Episodes" instead of a wild card in this instance because you'd get a lot of clips with a wild card (I'm assuming that isn't what you'd want).

```
<pass enabled="1" description="Hulu Subscriptions">
	<scan name="Hulu">
		<scan name="Your Subscriptions">
			<scan name="*">
				<scan name="Full Episodes">
					<queue name="*" />
				</scan>
			</scan>
		</scan>
	</scan>
</pass>
```

**Comment by samgreco** [comment]
Forgot about verbose.  Your example above works perfectly.
